### ISSUE TITLE
Create saw schema

### ISSUE THREAD

**Issue by antonnyst** [antonnyst/circular-entity-broker#2]

**Comment by Kebertr** [comment]
An example of your code with classes and properties:
@prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#> .

@base <http://ceb.ltu.se/broker/> .

:product a rdfs:Class .

:product:name a rdf:Property;
    rdfs:domain :product;
    rdfs:label "Product Name" ;
	rdfs:comment "The name of the product." .


:product:id a rdf:Property;
    rdfs:domain :product;
	rdfs:label "Product Number" ;
	rdfs:comment "The identifying number/id of the product." .

product:manufacturer a rdf:Property ;
    rdfs:domain :product;
	rdfs:label "Product Manufacturer" ;
	rdfs:comment "The company manufacturing the product" .



@prefix rdf:	<http://www.w3.org/1999/02/22-rdf-syntax-ns#>^^xsd:anyURI .
@prefix rdfs:	<http://www.w3.org/2000/01/rdf-schema#>^^xsd:anyURI .

@prefix sawblade: <http://ceb.ltu.se/components/sawblade>^^xsd:anyURI .
@prefix product: <http://ceb.ltu.se/broker/product>^^xsd:anyURI .

:sawblade a rdfs:Class;
     rdfs:subClassOf :product.

sawblade:teethGrade a rdfs:Property ;
    rdfs:domain :sawblade;
	rdfs:isDefinedBy <http://ceb.ltu.se/components/sawblade> ;
	rdfs:label "Teeth Grade" ;
	rdfs:comment "The fineness/grade of the teeth." .

sawblade:teethAmount a rdfs:Property ;
    rdfs:domain :sawblade;
	rdfs:isDefinedBy <http://ceb.ltu.se/components/sawblade> ;
	rdfs:label "Teeth Amount" ;
	rdfs:comment "The amount of teeth on the sawblade." .
